package org.flacro.po;

public class Tags {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tags.id
	 * @mbggenerated  Thu Nov 03 16:23:43 CST 2011
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tags.tag
	 * @mbggenerated  Thu Nov 03 16:23:43 CST 2011
	 */
	private String tag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tags.userid
	 * @mbggenerated  Thu Nov 03 16:23:43 CST 2011
	 */
	private Integer userid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tags.id
	 * @return  the value of tags.id
	 * @mbggenerated  Thu Nov 03 16:23:43 CST 2011
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tags.id
	 * @param id  the value for tags.id
	 * @mbggenerated  Thu Nov 03 16:23:43 CST 2011
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tags.tag
	 * @return  the value of tags.tag
	 * @mbggenerated  Thu Nov 03 16:23:43 CST 2011
	 */
	public String getTag() {
		return tag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tags.tag
	 * @param tag  the value for tags.tag
	 * @mbggenerated  Thu Nov 03 16:23:43 CST 2011
	 */
	public void setTag(String tag) {
		this.tag = tag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tags.userid
	 * @return  the value of tags.userid
	 * @mbggenerated  Thu Nov 03 16:23:43 CST 2011
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tags.userid
	 * @param userid  the value for tags.userid
	 * @mbggenerated  Thu Nov 03 16:23:43 CST 2011
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}
}