package org.flacro.po;

public class Users {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.id
	 * @mbggenerated  Thu Nov 03 16:23:43 CST 2011
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.username
	 * @mbggenerated  Thu Nov 03 16:23:43 CST 2011
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.gender
	 * @mbggenerated  Thu Nov 03 16:23:43 CST 2011
	 */
	private Integer gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.logo
	 * @mbggenerated  Thu Nov 03 16:23:43 CST 2011
	 */
	private String logo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.grade
	 * @mbggenerated  Thu Nov 03 16:23:43 CST 2011
	 */
	private Integer grade;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.id
	 * @return  the value of users.id
	 * @mbggenerated  Thu Nov 03 16:23:43 CST 2011
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.id
	 * @param id  the value for users.id
	 * @mbggenerated  Thu Nov 03 16:23:43 CST 2011
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.username
	 * @return  the value of users.username
	 * @mbggenerated  Thu Nov 03 16:23:43 CST 2011
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.username
	 * @param username  the value for users.username
	 * @mbggenerated  Thu Nov 03 16:23:43 CST 2011
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.gender
	 * @return  the value of users.gender
	 * @mbggenerated  Thu Nov 03 16:23:43 CST 2011
	 */
	public Integer getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.gender
	 * @param gender  the value for users.gender
	 * @mbggenerated  Thu Nov 03 16:23:43 CST 2011
	 */
	public void setGender(Integer gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.logo
	 * @return  the value of users.logo
	 * @mbggenerated  Thu Nov 03 16:23:43 CST 2011
	 */
	public String getLogo() {
		return logo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.logo
	 * @param logo  the value for users.logo
	 * @mbggenerated  Thu Nov 03 16:23:43 CST 2011
	 */
	public void setLogo(String logo) {
		this.logo = logo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.grade
	 * @return  the value of users.grade
	 * @mbggenerated  Thu Nov 03 16:23:43 CST 2011
	 */
	public Integer getGrade() {
		return grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.grade
	 * @param grade  the value for users.grade
	 * @mbggenerated  Thu Nov 03 16:23:43 CST 2011
	 */
	public void setGrade(Integer grade) {
		this.grade = grade;
	}
}